# Generated by Django 4.1.7 on 2023-03-08 07:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0002_alter_schedule_when'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email has already been registered.'}, max_length=100, unique=True, verbose_name='Email-address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', error_messages={'unique': 'This name has already been registered.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3, '닉네임은 3자 이상이어야합니다.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='pick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='idols.idol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profileImg',
            field=models.URLField(blank=True, null=True),
        ),
    ]
