# Generated by Django 4.1.7 on 2023-03-15 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.MinLengthValidator(3, '닉네임은 3자 이상이어야합니다.')]),
        ),
    ]
