# Generated by Django 4.1.7 on 2023-03-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '이미 사용중인 이메일입니다.'}, max_length=100, null=True, unique=True, verbose_name='Email-address'),
        ),
    ]
