# Generated by Django 4.1.7 on 2023-03-20 08:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0002_alter_schedule_when'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.MinLengthValidator(2, '이름은 2자 이상이어야합니다.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='pick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='idols.idol'),
        ),
    ]
