# Generated by Django 4.1.7 on 2023-03-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImg',
            field=models.URLField(blank=True, default='https://audition.hanbiton.com/images/common/img_default.jpg', null=True),
        ),
    ]
