# Generated by Django 4.1.7 on 2023-03-04 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idols', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email-address'),
        ),
    ]
