# Generated by Django 4.1.7 on 2023-03-04 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0001_initial'),
        ('users', '0005_user_pick_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='idols.idol'),
        ),
    ]
