# Generated by Django 4.1.7 on 2023-03-11 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('content', models.CharField(default='', max_length=100)),
                ('when', models.DateTimeField(default=datetime.datetime(2023, 3, 11, 7, 40, 45, 938, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name_plural': 'User Report',
            },
        ),
    ]
