# Generated by Django 4.1.7 on 2023-03-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_report_content_remove_report_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='when',
        ),
    ]
