# Generated by Django 4.1.7 on 2023-03-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_report_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
