# Generated by Django 4.1.7 on 2023-03-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_report_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='owner',
        ),
        migrations.AddField(
            model_name='user',
            name='reports',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='users.report'),
        ),
    ]
