# Generated by Django 4.1.7 on 2023-03-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_report_owner_user_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='owner',
            field=models.CharField(default='', max_length=100),
        ),
    ]
