# Generated by Django 4.1.7 on 2023-03-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_who_report_whoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
