# Generated by Django 4.1.7 on 2023-03-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idol_group', models.CharField(blank=True, choices=[('girlGroup', 'girlGroup'), ('BoyGroup', 'BoyGroup')], max_length=30, null=True)),
                ('idol_solo', models.CharField(blank=True, choices=[('girlSolo', 'girlSolo'), ('boySolo', 'boySolo')], max_length=30, null=True)),
                ('idol_name', models.CharField(max_length=7)),
                ('idol_profile', models.URLField(max_length=10000)),
                ('idol_anniv', models.DateField()),
                ('idol_birthday', models.DateField()),
                ('idol_gender', models.CharField(choices=[('women', 'women'), ('Man', 'man')], max_length=5)),
                ('idol_schedule', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Our_Idols',
            },
        ),
    ]
