# Generated by Django 4.1.7 on 2023-03-04 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_category_options_remove_category_name_and_more'),
        ('idols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.AddField(
            model_name='idol',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idols', to='categories.category'),
        ),
        migrations.RemoveField(
            model_name='idol',
            name='idol_schedule',
        ),
        migrations.AddField(
            model_name='idol',
            name='idol_schedule',
            field=models.ManyToManyField(related_name='idols', to='idols.schedule'),
        ),
    ]
