# Generated by Django 4.1.7 on 2023-03-09 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 6, 36, 12, 744905, tzinfo=datetime.timezone.utc)),
        ),
    ]
