# Generated by Django 4.1.7 on 2023-03-20 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 11, 24, 34, 604694, tzinfo=datetime.timezone.utc)),
        ),
    ]
