# Generated by Django 4.1.7 on 2023-03-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0002_schedule_idol_category_remove_idol_idol_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idol',
            name='category',
        ),
    ]
