# Generated by Django 4.1.7 on 2023-03-16 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0003_alter_schedule_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='ScheduleContent',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 6, 54, 16, 259185, tzinfo=datetime.timezone.utc)),
        ),
    ]
