# Generated by Django 4.1.7 on 2023-03-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0003_remove_idol_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name_plural': 'Idol-Schedules'},
        ),
    ]
