# Generated by Django 4.1.7 on 2023-03-16 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0004_remove_schedule_schedulecontent_alter_schedule_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 7, 56, 36, 40113, tzinfo=datetime.timezone.utc)),
        ),
    ]
