# Generated by Django 4.1.7 on 2023-03-16 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0005_alter_schedule_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 9, 35, 9, 233083, tzinfo=datetime.timezone.utc)),
        ),
    ]
