# Generated by Django 4.1.7 on 2023-03-17 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0006_alter_schedule_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 11, 33, 0, 211700, tzinfo=datetime.timezone.utc)),
        ),
    ]
