# Generated by Django 4.1.7 on 2023-03-22 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0007_alter_schedule_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='idol_name_en',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='idol',
            name='idol_name_kr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 6, 12, 40, 833345, tzinfo=datetime.timezone.utc)),
        ),
    ]
