# Generated by Django 4.1.7 on 2023-03-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0007_rename_name_schedule_scheduletitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='ScheduleType',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='type.Category'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ScheduleTitle',
            field=models.CharField(max_length=150, verbose_name='title.Category'),
        ),
    ]
