# Generated by Django 4.1.7 on 2023-03-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0008_schedule_scheduletype_alter_schedule_scheduletitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='ScheduleType',
            field=models.CharField(blank='', max_length=15, null=True, verbose_name='type.Category'),
        ),
    ]
