# Generated by Django 4.1.7 on 2023-03-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0008_alter_idol_idol_name_en_alter_idol_idol_name_kr_and_more'),
        ('idols', '0009_alter_schedule_when'),
    ]

    operations = [
    ]
