# Generated by Django 4.1.7 on 2023-03-22 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0010_merge_20230322_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 19, 1, 11, 961867)),
        ),
    ]
