# Generated by Django 4.1.7 on 2023-03-23 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0010_alter_idol_boy_group_alter_idol_girl_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 21, 58, 23, 153427)),
        ),
    ]
