# Generated by Django 4.1.7 on 2023-03-10 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0010_alter_schedule_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 2, 17, 20, 39265, tzinfo=datetime.timezone.utc)),
        ),
    ]
