# Generated by Django 4.1.7 on 2023-03-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0011_schedule_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='ScheduleTitle',
            field=models.CharField(blank='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ScheduleType',
            field=models.CharField(blank='', max_length=150, null=True),
        ),
    ]
