# Generated by Django 4.1.7 on 2023-03-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0010_alter_schedule_when'),
        ('idols', '0012_alter_schedule_when'),
    ]

    operations = [
    ]
