# Generated by Django 4.1.7 on 2023-03-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0013_schedule_end_time_schedule_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
