# Generated by Django 4.1.7 on 2023-03-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0013_merge_20230325_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(),
        ),
    ]
