# Generated by Django 4.1.7 on 2023-03-06 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0014_alter_schedule_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
    ]
