# Generated by Django 4.1.7 on 2023-03-10 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0023_alter_schedule_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='idol_profile',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 7, 46, 2, 99429, tzinfo=datetime.timezone.utc)),
        ),
    ]
