# Generated by Django 4.1.7 on 2023-03-10 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0025_alter_schedule_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 8, 4, 7, 715062, tzinfo=datetime.timezone.utc)),
        ),
    ]
