# Generated by Django 4.1.7 on 2023-03-11 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0042_alter_schedule_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 8, 11, 15, 136544, tzinfo=datetime.timezone.utc)),
        ),
    ]
