# Generated by Django 4.1.7 on 2023-03-12 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0060_alter_schedule_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 8, 33, 13, 771659, tzinfo=datetime.timezone.utc)),
        ),
    ]
