# Generated by Django 4.1.7 on 2023-03-12 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0063_alter_schedule_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 9, 25, 14, 231700, tzinfo=datetime.timezone.utc)),
        ),
    ]
