# Generated by Django 4.1.7 on 2023-03-13 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0066_alter_schedule_when'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='description',
            new_name='ScheduleContent',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 1, 24, 15, 583386, tzinfo=datetime.timezone.utc)),
        ),
    ]
