# Generated by Django 4.1.7 on 2023-03-14 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0068_alter_idol_idol_name_alter_schedule_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='idol_name',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 1, 21, 50, 332437, tzinfo=datetime.timezone.utc)),
        ),
    ]
