# Generated by Django 4.1.7 on 2023-03-14 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0069_alter_idol_idol_name_alter_schedule_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 4, 47, 17, 740252, tzinfo=datetime.timezone.utc)),
        ),
    ]
