# Generated by Django 4.1.7 on 2023-03-15 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0070_alter_schedule_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 2, 38, 54, 288848, tzinfo=datetime.timezone.utc)),
        ),
    ]
