# Generated by Django 4.1.7 on 2023-03-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0002_alter_schedule_when'),
        ('usersCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercalendar',
            name='pick',
            field=models.ManyToManyField(to='idols.idol'),
        ),
    ]
