# Generated by Django 4.1.7 on 2023-03-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercalendar',
            options={'verbose_name_plural': "User's Calendar"},
        ),
    ]
