# Generated by Django 4.1.7 on 2023-03-06 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersCalendar', '0003_usercalendar_end_time_usercalendar_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercalendar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersCalendar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercalendar',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
