# Generated by Django 4.1.7 on 2023-03-06 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersCalendar', '0004_alter_usercalendar_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercalendar',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='usercalendar',
            name='start_time',
        ),
    ]
