# Generated by Django 4.1.7 on 2023-03-04 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0001_initial'),
        ('categories', '0002_rename_categories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.ForeignKey(default='', max_length=150, on_delete=django.db.models.deletion.CASCADE, to='idols.idol'),
        ),
    ]
