# Generated by Django 4.1.7 on 2023-03-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(default='', max_length=150),
        ),
    ]
