# Generated by Django 4.1.7 on 2023-03-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_alter_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
