# Generated by Django 4.1.7 on 2023-03-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
