# Generated by Django 4.1.7 on 2023-03-06 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_alter_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
    ]
