# Generated by Django 4.1.7 on 2023-03-09 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('usersCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='usersCalendar.usercalendar'),
        ),
        migrations.AddField(
            model_name='photo',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='usersCalendar.usercalendar'),
        ),
    ]
