# Generated by Django 4.1.7 on 2023-03-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_photo_end_time_photo_start_time_video_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='video',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='video',
            name='start_time',
        ),
    ]
